### ISSUE TITLE
Use keyword signatures

### ISSUE THREAD

**Issue by kkaefer** [cjntaylor/node-cmake#17]
The previous version 1.x used keyword signatures for targets. I'm trying to update my project (https://github.com/mapbox/mapbox-gl-native) to 2.x, but am getting this error:

> CMake Error at cmake/node.cmake:35 (target_link_libraries):
>   The plain signature for target_link_libraries has already been used with
>   the target "mbgl-node".  All uses of target_link_libraries with a target
>   must be either all-keyword or all-plain.
> 
>   The uses of the plain signature are here:
> 
>    * cmake/NodeJS.cmake:583 (target_link_libraries)

Why was the signature changed back to the (old?) plain syntax?

**Comment by cjntaylor** [comment]
node-cmake has never used keyword signatures, I even went back and double checked;

This is where the libraries variable is set (in 1.x):
https://github.com/cjntaylor/node-cmake/blob/1.3.0/variants/NodeJS.cmake#L119

This is where target_link_libraries is called (in 1.x):
https://github.com/cjntaylor/node-cmake/blob/1.3.0/FindNodeJS.cmake#L487

This error is typically because you've added scope specifiers, like "PUBLIC" or "PRIVATE" to your `target_link_libraries` command. I generally don't do this and don't plan to support it because strange things happen with 'PRIVATE' scoped libraries. Especially with shared libraries, missing symbols are highly likely. Omitting these keywords is mostly equivalent to "PUBLIC" and behaves as expected. Most cmake examples use the plain format.

**Comment by kkaefer** [comment]
I've debugged this further, since I'm still seeing the above error message. It turns out that:

- On non-Windows platforms, `NodeJS_LIBRARIES` was empty, so the call to `target_link_libraries` didn't contain any parameters. Apparently CMake doesn't count this as a call, so the call type doesn't get tainted.
- Instead, it used `set_target_properties` to set the linker flags in the 1.x series, while the 2.x series uses.

I believe the 1.x branch was correct in not using `target_link_libraries` for setting linker flags. What is the reason for moving the LINK_FLAGS to `target_link_libraries`?

**Comment by kkaefer** [comment]
CMake docs say this:

> Use the LINK_FLAGS target property to add link flags explicitly. The flags will then be placed at the toolchain-defined flag position in the link command.

**Comment by kkaefer** [comment]
It also seems like node-cmake uses keyword signatures for pretty much all other calls, but not for `target_link_libraries`.

**Comment by cjntaylor** [comment]
I've gone ahead and merged this change, since it isn't detrimental (more specifically, it should be backwards compatible). Your reference to the CMake docs only applies for CMake >= 3.7+; this project only requires features from CMake >= 3.1+, and unless there is some compelling reason otherwise, I intend to hold the CMake version dependency to 3.1.

**Comment by cjntaylor** [comment]
> On non-Windows platforms, NodeJS_LIBRARIES was empty, so the call to target_link_libraries didn't contain any parameters. Apparently CMake doesn't count this as a call, so the call type doesn't get tainted.

😱  - good catch. I'll have to look through the CMake documentation to see when this happened, but this is new behaviour as of one of the 3.0 versions. Prior to this, `target_link_libraries` was the recommended mechanism for adding all linker flags, in addition to libraries. I've mostly tested this with older versions of CMake on windows; I'll make sure this rule gets accounted for in post 2.2.1 updates.
