### ISSUE TITLE
Don't force CXX_STANDARD

### ISSUE THREAD

**Issue by kkaefer** [cjntaylor/node-cmake#18]
The previous 1.x branch allowed [configuring the CXX_STANDARD](https://github.com/cjntaylor/node-cmake/blob/86d668a56a00f0fccfa01d0ccd6888f5ba454532/FindNodeJS.cmake#L413-L421) by setting `NodeJS_CXX_STANDARD`. The current branches forces a CXX_STANDARD of 11. What's the reason for this change?

**Comment by cjntaylor** [comment]
The 2.0 branch only supports node after io.js it was merged back into it (essentially, >= 4.0). This is inline with the LTS, which is the oldest version officially supported by node.js. After this point, the V8 API node consumes uses C++11 syntax. Modules will fail to build without enforcing the standard.

**Comment by kkaefer** [comment]
@cjntaylor Sorry, should've made this clearer: We're using C++14, and forcing C++11 means that the compiler won't accept our code. This ticket isn't about using a version prior to C++11.

**Comment by cjntaylor** [comment]
Do you have a suggestion on what the interface should be? The standard is set here only:
https://github.com/cjntaylor/node-cmake/blob/master/NodeJS.cmake#L596

Would calling set_target_properties a second time fix the problem, e.g:
```cmake
add_nodejs_module(${PROJECT_NAME} <SOURCE AND HEADER FILES GO HERE>)
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 14)
```

Can you check with your project? I'm curious because its handy to have it enforcing at least C++11 to prevent build failures if its unspecified. The alternatives would be to define the standard as an overridable variable (which you'd set prior to any call to add_nodejs_module) or possibly the compile feature configuration CMake added in 3.1+. The latter is a bit tricky because its a moving target; I'd have to work out exactly what parts of C++11 V8 is using which will vary.

**Comment by daniel-j-h** [comment]
Confirming here - setting

`set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 14)`

on the module's target works fine and compiles our projects with C++14.
