### ISSUE TITLE
Unable to extract header archive checksum

### ISSUE THREAD

**Issue by jhermsmeier** [cjntaylor/node-cmake#19]
**node-cmake version:** `2.1.1`
**Node versions**: `v6.9.4`, `v4.7.2`
**OS**: Ubuntu 12.04.5 LTS

**Output:** (for full output, see Travis CI builds below)
```
-- Enabling assertions
-- Downloading: https://nodejs.org/download/release/v6.9.4/SHASUMS256.txt
CMake Error at cmake/NodeJS.cmake:280 (message):
  Unable to extract header archive checksum
Call Stack (most recent call first):
  CMakeLists.txt:93 (nodejs_init)
```

**Travis CI Builds:**
- https://travis-ci.org/Project-OSRM/node-osrm/jobs/194239977
- https://travis-ci.org/Project-OSRM/node-osrm/jobs/194239975

**Comment by lstkz** [comment]
I have the same version on Ubuntu 14, but it works on Mac.

**Comment by cjntaylor** [comment]
Typically, this is caused by either (1) The checksum file failing to download, or (2) The checksum file not saving to disk. I suspect that Travis may be the cause of the issue here; is it allowing the checksum file to be written to disk during the build? Does it allow your build to download files during the build process?

I've double checked that it this version's checksum file contains a header entry per the regex search:
http://regexr.com/3f5de

Does this behaviour persist if you build locally against the same version of node?

**Comment by kkaefer** [comment]
This could be an instance of the issue described in https://github.com/cjntaylor/node-cmake/pull/23

**Comment by jhermsmeier** [comment]
Aah, might be that Travis has the file cached in this particular instance, triggering the #23 case.
It does work fine locally, and with other repos running on Travis.

**Comment by cjntaylor** [comment]
Do you still have this behaviour on 2.2.0? I'm still skeptical that something deeper is going on within Travis. Is the repo filesystem R/W during a travis build? This would occur if the file couldn't be saved to disk.

Contrary to what #23 might lead you to believe, I do download the files to a temporary location (local to the project, specifically `${CMAKE_CURRENT_BINARY_DIR}/temp`) validate them before saving them. Subsequent runs remove any temporary files before attempting to download again, and just to be sure, 2.2.0 removes the whole temporary directory when nodejs_init is called.

**Comment by rayglover-ibm** [comment]
I just bumped in to the same error; this is due to libcurl not supporting https in Ubuntu 12 (the default linux distro in travis). It would be much easier to diagnose such issues if the download log was included in the output, i.e. `file(DOWNLOAD ... LOG ...)`.

As for travis, use `dist: trusty` instead.

**Comment by cjntaylor** [comment]
Thanks for the suggestion. I've added this in 2.3.0; the download output is written to `${TEMP}/download.log` for debugging. This file will only persist for one execution; and will be cleared on subsequent executions after a successful download (since `${TEMP}` is removed).
