### ISSUE TITLE
targetname_BUILD macro

### ISSUE THREAD

**Issue by kkaefer** [cjntaylor/node-cmake#21]
https://github.com/cjntaylor/node-cmake/blob/4ae8a5ca32f672aeb6259f52d3881780a95aea8b/NodeJS.cmake#L573 defines a `targetname_BUILD` macro, and the comment states that it's for symbol visibility on Windows. Can yo please explain what it does?

Defining a macro like this makes it impossible to use target names that contain dashes, since macros can't contain dashes.

**Comment by kkaefer** [comment]
Background is that I don't see it being used anywhere.

**Comment by cjntaylor** [comment]
This **define** (-D or /D parameter on the command line), not macro, is provided for users of node-cmake who use symbol visibility. Basically, when you dynamically link libraries (dlls) under windows, you're required to use the `__declspec(dllexport)` and `__declspec(dllimport)` markers to ensure that the symbols in the library are usable when compiling. Since node modules are just renamed shared libraries, this also applies to them.

This process is much simpler under *nix platforms, where a single marker is used to set symbol visibility `__attribute__ ((visibility ("default")))`. You can use this symbol both during build and linking without modifying it.

On windows, however, there are the two different symbols that you use at different times. `__declspec(dllexport)` needs to be used when compiling and linking the library, and `__declspec(dllimport)` needs to be used when you link another library or binary against the library, to ensure that it defines the symbol properly. There isn't any good way to know which of these two states you are in automatically (via preprocessor macros, or otherwise), so this is a typical solution to the problem. Most programs define some sort of `"X"_BUILD` define that the developer uses to pivot between these two terms. More info and an example here: https://gcc.gnu.org/wiki/Visibility

The additional define also creates a problem; it needs to be unique for each library, otherwise you run the risk of inadvertently using the wrong `__declspec` when you don't intend to. This is why its defined as `${NAME}_BUILD`. I hadn't considered the invalid character names issue, but I can address that in the next release. I'll sanitize the NAME variable before generating the define to strip out any invalid define characters (likely converting them to underscores), which should solve your issue.

Thanks for the heads up 👍

**Comment by cjntaylor** [comment]
So after investigating this further, I determined why I defined this the way it is. Per the Node.js addon documentation:

> The module_name must match the filename of the final binary (excluding the .node suffix).

(From right above [this](https://nodejs.org/api/addons.html#addons_building))

This means that the node module name can't legally contain dashes, since they're not valid in a C identifier. Since `${NAME}` is used to generate the module name (e.g. `${NAME}.node`), the behaviour is correct.

This is mostly reflected in the MODULE_NAME define I also include, to make this easier for developers in code (just use the macro instead of hard coding the name). `${NAME}_BUILD` also has this restriction but more as a side effect.

However, there is possible bad behaviour when using node-cmake. Instead of my original plan, I'm adding an error case to the function to ensure that `${NAME}` is within spec. This should both address your issues (apologies, but I can't do anything about the addon requirements, you'll have to take that up with the node devs), and make the behaviour more straightforward.

**Comment by cjntaylor** [comment]
Addressed in 2.2.0

**Comment by kkaefer** [comment]
You're right that the node module name may not contain illegal characters, but there's no connection between the node module name and the `${NAME}_BUILD` macro. Furthermore, there is no connection between the CMake target name and the binary name other than that it defaults to the target name. However, this can be changed with a call to `set_target_properties(target PROPERTIES OUTPUT_NAME binaryname)`

**Comment by kkaefer** [comment]
Commit is https://github.com/cjntaylor/node-cmake/commit/0bc58b78e55840c693388bff7388bd103c70069d

**Comment by kkaefer** [comment]
This could be addressed by changing the signature of `add_nodejs_module` to accept a `target` and a `module_name` argument, which can be distinct, or by replacing the `add_nodejs_module` by having the user to manually call `add_library`, then adding a call to "convert" that target to a node module.
