### ISSUE TITLE
Allow passing options to cmake via ncmake

### ISSUE THREAD

**Issue by daniel-j-h** [cjntaylor/node-cmake#25]
At the moment I can't see a way to pass CMake options to the cmake invocation through ncmake.

Here's how this could look like:

    ncmake rebuild -- -DKEY0=VAL0 -DKEY1=VAL1

which should pass the CMake `-D` options through to the cmake command.

Why is this needed? In a large code base optional node bindings may need cmake support, think

    cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_NODE_BINDINGS=On -DMORE=Options

but at the moment using ncmake as a build system driver this is not possible.

**Comment by cjntaylor** [comment]
This is a good idea, so I'll work on this for the next release. It's a little bit tricky because I'll have to collapse -D flags somehow; I have to set a few to get the correct behaviour to mirror node-gyp's output format (specifically CMAKE_BUILD_TYPE needs to be set appropriately). In this case, you can already manipulate this by setting "-d" to switch from Release to Debug (same as node-gyp).

I'll also have to find a way to get yargs (which is what I use to parse the command line arguments) to ignore arguments after the '--', but that should be doable.

**Comment by cjntaylor** [comment]
Fixed in 2.3.0
