### ISSUE TITLE
NodeJS_LIBRARIES is empty on MingW

### ISSUE THREAD

**Issue by KrishnaPG** [cjntaylor/node-cmake#31]
Encountering many linker errors, such as:
````
[100%] Linking CXX shared library abc.node
(main.cc.obj):main.cc:(.text+0x1d): undefined reference to `v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)'
````
Turns out that the `${NodeJS_LIBRARIES}` is empty and not populated with the node js libraries. How to correct this? Environment: `-- NodeJS: Using node, version v6.9.2` on Windows 10 with MingW64

**Comment by cjntaylor** [comment]
MinGW isn't explicitly supported by the current version of node-cmake. I don't have a particularly great test environment for it, and to my knowledge, it's not immensely endorsed by the node.js community either (`node-gyp` instructs users to install the community edition of visual studio to compile).

Part of the issue is also that MinGW is a bit of a hybrid system, which behaves sort of like the visual studio toolchain (VCC), and sort of like gcc/clang. This makes compiling node modules difficult, since they're dynamically resolved at runtime (via dlopen/equivalent). On gcc/clang based platforms, the module isn't linked against any libraries at all. It's sufficient to the compiler to provide the headers, and to have the linker be told that missing symbols in the library will be resolved later.

Windows, on the other hand, requires that at least a stub of the symbol is resolved during link time. This is why on that platform, `${NODE_LIBRARIES}` is populated against system `.lib` files, and one provided by the node.js build team (`node.lib`) on the release server for download. Adding these libraries provides the stubs to satisfy the linker, but everything is still resolved at runtime. Just one of the many ways VCC is different then its compiler brethren.

The problem with MinGW then, is that its sort of does both. I would have expected (and based on the `node-gyp` build), that it would behave more like gcc/clang, where it would allow the symbols to be undefined during the link step. `node-gyp` doesn't seem to do anything special for MinGW, but then again, I don't know that they explicitly support it either.

All of this said, you could attempt to have it link against the libraries if you wanted. In the `NodeJS.cmake` file in your project, you can replace every instance of the condition `if(WIN32)` with `if(WIN32 OR MINGW)`. This will attempt to do the same things the system does under windows with the MinGW compiler. Can you let me know if that works / you have any other issues? If so, I'll add it to the next release so you don't have to manually make this patch.

**Comment by cjntaylor** [comment]
Closing due to no response, and no change on the MinGW support front.
