### ISSUE TITLE
32 bit module not working on 64 bit NodeJS

### ISSUE THREAD

**Issue by gamelaster** [cjntaylor/node-cmake#32]
```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
```
Works only after by using:
`ncmake configure -g "Visual Studio 15 2017 Win64"`

**Comment by cjntaylor** [comment]
This is expected behaviour. Node.js modules MUST match the architecture of the executing node binary; if your `node.exe` (in this case) is compiled for 64-bit, modules must be compiled as 64 bit as well.

As for `ncmake` / `node-cmake`, what you've done is exactly what is needed. You need to inform cmake that the module needs to be built for 64-bit, which in the CMake ecosystem is defined/controlled by the generator. In this case, you had to specify it because the default generator on your system is for 32-bit. How the default generator is selected is prevue of cmake and not under my control; all that can be done is to explicitly configure it, which is the hook I provide with `-g`.

You can certainly raise the issue of which generator is selected as the "default" with cmake directly: https://gitlab.kitware.com/cmake/cmake/issues

As a developer, I'd expect that on a 64-bit system, the 64-bit version of the compiler would be the default (but that doesn't seem to be the case).

I will add this to my list of things to consider for the next iteration of this package, but its complicated. I'd need to think about a way to generalize this so that the correct compiler is selected at runtime; this would likely couple to determining the architecture of the `node.exe` executable. I'm not too keen on this, since `node-cmake` doesn't presently have any hard coupling to having node.js installed (it will potentially interrogate the executable if its installed but it isn't a requirement). One of my hard requirements has always been that this module works without a direct install of node. There are several users of this package that build a node module in concert with a larger system of binaries and expect that node-cmake provides all of its own build requirements without a node binary.

A lesser but second issue is with the version-dependence of CMake generators and visual studio. The generators are named based on specific supported versions of Visual Studio (2017, 2015, etc), but will only work if that specific version is installed. I'd have to determine this myself as part of selecting the generator since CMake doesn't provide this functionality.

Its a good point though. This is a bit of an unhandled failure mode if `ncmake rebuild` is put in the postinstall step of a node module where the architecture is ambiguous. I'm open to suggestions, if you have any.

**Comment by toddwong** [comment]
But it default to 32 bit generator on 64 bit OS. Should be nicer if it picks generator base on installed node arch or OS arch.

**Comment by cjntaylor** [comment]
I've attempted to address this in 2.4.0, by using the `-A` parameter when targeting Visual Studio (https://gitlab.kitware.com/cmake/cmake/issues/16339).

Like I said before, the problem here is that despite what you might think, your assertion is wrong. The "default" generator that CMake picks is based on an internal algorithm that I don't have control over. It *might* pick the 32-bit one by default, but it depends on what you have installed / what version of CMake you're running.

However, according to that issue, the `-A` parameter can be passed to the `cmake` binary to select the compiler version, e.g. `cmake -A x64 -G "Visual Studio 14 2015"` is equivalent to `cmake -G "Visual Studio 14 2015 Win64"`. 

Since the `cmake` call fails if this parameter is specified with a non-Visual Studio generator, and there isn't a guarantee that the "default" generator is even a Visual Studio one, I'm still requiring that the generator flag (`-g/--generator`) is actually set every time (this won't happen by default). I'm uncomfortable having this be a default as I don't want my existing users to run into a different version of the failure mode where this breaks because it is specified. The benefit is that you don't have to manually specify the architecture; it'll attempt to match the version of `node` running `ncmake`.

I may revisit this last decision later, if I can suss out a cleaner way of having this on by default (probably involving checking the default generator, which is tricky). Reopen this issue if it continues to be a problem.

**Comment by toddwong** [comment]
Very nice! 
You are right, I did underestimate the issue.
I didn't know the -A options before, very nice to learn!
