### ISSUE TITLE
Support specify build directory

### ISSUE THREAD

**Issue by toddwong** [cjntaylor/node-cmake#33]
Need to deploy prebuild binaries to windows servers (without visual studio installed) with different versions of node installed. It is painful to reconfigure every time.

**Comment by cjntaylor** [comment]
Added in 2.4.0 via the `-o/--output` argument. Note that you'll need to specify this option with each execution of ncmake, and that the module-finding algorithm included in this module hasn't been updated (since I have no way of knowing what you'd set this to). You'll have to `require()` the module yourself using the path directly.

**Comment by toddwong** [comment]
@cjntaylor that's very nice!  Many thanks!

It's quite OK to specify this option with each execution of ncmake. It's only needed before deploying. Wouldn't be too often.

For the `require()`, it would be easier to overcome (I have some pre-depoly script anyway).
