### ISSUE TITLE
Use ANSI version windows APIs explicitly in win_delay_load_hook.c

### ISSUE THREAD

**Issue by toddwong** [cjntaylor/node-cmake#34]
Replace
`GetModuleHandle`
`GetModuleFileName`
`PathFindFileName`
`PathRemoveFileSpec`
`PathAppend`
to
`GetModuleHandleA`
`GetModuleFileNameA`
`PathFindFileNameA`
`PathRemoveFileSpecA`
`PathAppendA`

And replace TCHAR with CHAR corresponding

**Comment by cjntaylor** [comment]
The `win_delay_load_hook` in use here is a modified version of the one in use by `node-gyp` to handle dll loading (https://github.com/EvolveLabs/electron-updater-tools/blob/master/src/delay_load_hook.h)

In all the cases I've seen, the calls specifically do not use the explicit ANSI version. Since this works across the board, I'm hesitant to change this unless its absolutely necessary and won't break existing users of `node-cmake`. Can you please explain why you need the explicit ANSI calls?

If you need this for your specific use case, please keep in mind that `NodeJS.cmake` is copied to and managed by each project that uses this build system, which allows you to have your own customizations by editing this file. I fully expect that `NodeJS.cmake` is checked in with your project. You can make changes you need in the file for your specific use case to support something like this. 

Specifically, you can edit the `nodejs_generate_delayload_hook` function in the file after the first `file(WRITE  ${OUTPUT} "")` line (https://github.com/cjntaylor/node-cmake/blob/dev/NodeJS.cmake#L49). I use the script in [lib/embed.js](../tree/dev/lib/embed.js) to convert a file into `file(APPEND)` commands for this function; it takes a single path to the file you want to convert. If it's easier, edit [src/win_delay_load_hook.c](../tree/dev/src/win_delay_load_hook.c) first, and then run this script to generate what needs to go into `NodeJS.cmake`:

```
node lib/embed.js src/win_delay_load_hook.c
```

Copy the output (or buffer to the clipboard) and replace **ALL** of the `file(APPEND)` lines in the function.

**Comment by toddwong** [comment]
I'm using Visual Studio 2017. The charset of the generated project is set to UNICODE.  This will cause compilation warning, and runtime malfunction.

The problem is: 
With UNICODE charset set, macro PathFindFileName will expand to PathFindFileNameW, which accept a WCHAR(2bytes) string and return a WCHAR string, let's say, L"node.exe", which will be implicitly casted to a LPSTR, which is a char(1byte) string, which would be "n" instead of "node.exe" on little-endian platform (or "" on big-endian platform), because L'n' == (unsigned short)0x006e == {'n', '\0'} on little-endian platform.

PS: of course , there is no big-endian Windows platform.

**Comment by toddwong** [comment]
I made a PR #35
Last time, I couldn't get the TEXT() macro work, so I suggested we change to UNICODE api explicitly. But actually it works (VS malfunction?).  
I do agree with the "works across the board" concern, so we'd fix this that way.

**Comment by cjntaylor** [comment]
Thanks for this change. I tested it out as best I could and can't find any major issues, so I've gone ahead and released this as 2.5.0.

Let me know if you have any further issues. I appreciate the PR 😄
