### ISSUE TITLE
Looking for a home for my FindNojeJS.cmake

### ISSUE THREAD

**Issue by hokiedsp** [cjntaylor/node-cmake#43]
Hey, this is rather an odd request, but I've written a `find_package()` routine to find Node.JS in CMake, and I'm looking for its permanent home, to be a part of a native addon builder node package.

https://github.com/hokiedsp/cmake-modules/blob/master/FindNodeJS.cmake

It is a fairly complete routine (downloads the version-matched node/nw/electron runtime files on the fly).  The usage (supported components and output variables) is included in the file's header comment block.

I've been using it to build native addons independent of node (I'm a node.js newbie, coming from native side) and it has been working well for what I do. I suspect there are some overlapping features to your `NodeJS.cmake` (like runtime downloading) but if there is any interest in reviving(?) the find_package() support, I could help merging them. The only caveat of my file is that it has not been tested on non-Windows environment.

Thanks

**Comment by computerquip-streamlabs** [comment]
I'm not sure I get the point of this. NodeJS.cmake is a module itself that you just have to copy and paste into your cmake modules directory and include. What does find_package here bring to the table?

**Comment by cjntaylor** [comment]
Very late, but I agree with @computerquip-streamlabs. The original version of this package tried to use `find_package()` and it had a lot of limitations, so much so that I completely rewrote it for 2.0 without it to address them. I think it works pretty well exactly as is, and conforming to `find_package()` semantics, which is meant for finding libraries and modules to link against, is either neutral or slightly worse.

Is there something that you do that I don't? `node-cmake` also works completely independently of node and provides a complete system for building modules, so I'm struggling to see how these are different. 

Your caveat of no windows testing is also a no-go for me; I go to great lengths to try to make sure this works across Windows, Linux and MacOS, even though I don't regularly use Windows myself. I've already established a policy that I won't include / will reject any feature that doesn't work in all contexts, and that isn't going to change. The point of a tool like this is that it needs to work everywhere node does, and node supports all three platforms.
