### ISSUE TITLE
CXX options in add_nodejs_module

### ISSUE THREAD

**Issue by tdp2110** [cjntaylor/node-cmake#46]
First, thanks for your work on a great project. My issue: it would be nice to be able to pass compiler options to `add_nodejs_module` (I'm specifically interested in `CXX_STANDARD`, currently hardcoded to 11, but I'd imagine other options might be useful as well). Cheers!

**Comment by cjntaylor** [comment]
Node.js requires a minimum of C++11 to compile at this point (due to inheriting this requirement from V8). I've long held (see #18) that I want this to work "out of the box" for most people, so I need to make sure that at least some minimum is set. 

`add_nodejs_module` creates a standard CMake library target based on the name you specify, which allows you to override this behaviour with an additional call to set_target_properties:

```
set_target_properties(<module_name> PROPERTIES CXX_STANDARD 14)
```

I don't want to expand the scope of `add_nodejs_module` too much as parsing / handling arguments in CMake is pretty tricky and potentially confusing to users. For now, I believe that the ability to modify the target after this call (which is a standard design pattern in CMake, see `target_link_libraries`, `target_include_directories`, etc.) is sufficient. Please let me know (with examples, if possible :wink:) if this isn't the case for you.

**Comment by tdp2110** [comment]
thanks, works on my box 👍
