### ISSUE TITLE
How can I link third party library with node-cmake?

### ISSUE THREAD

**Issue by jackyko1991** [cjntaylor/node-cmake#52]
In traditional CMakeLists, binaries should be linked with third party libraries with the line  `target_link_libraries(MyApp LibraryToLink)`

How can this be done with node cmake?

**Comment by cjntaylor** [comment]
`add_nodejs_module(<NAME>)` just wraps a call to add_library, passing the first argument to it directly. This means you can call `target_link_libraries` just like your example above, passing the same first argument to both:

```cmake
add_nodejs_module(foo foo.c)
target_link_libraries(foo PUBLIC ${BAR_LIBRARY})
```

I went to great lengths to ensure that `node-cmake` follows normal CMake conventions when setting things up, so that other functions like this would just work normally. Please let me know if this is not the case.
